<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div id="holder">
<div class="headercontainer">
<div class="headercontent">
<img class="logo" src="<?php echo $this->basePath() . '/images/main_logo.png'; ?>" width="285" height="51" alt="LOGO" />
<p class ="login"><a style="color:#FFF" class="feedlink" href="#">Register</a> | <a style="color:#FFF" class="feedlink" href="#">Login</a></p>
		<form class="search" method="get" id="searchform" action="">
				<label style="color:#FFF" for="s">Search:</label>
				<input class="searchbox" type="text" value="" name="s" id="s" size="14" />
				<input type="hidden" id="searchsubmit" value="Search" />
		</form>
        <div class="clear"></div>
		<ul class="nav">
			<li class="current_page_item"><a href="index.html">MY GOALS</a></li>
			<li><a href="styles.html">FRIENDS GOALS</a></li>
			<li><a href="layouts.html">SETTINGS</a></li>
			<li><a href="empty.html">ABOUT</a></li>
		</ul>
</div>
<div class="clear"></div>
</div>
    
  
<div class="mainconainer">
<div class="maincontent">
            <?php echo $this->content; ?>
</div>
</div>		

<div class ="footercontainer">
<div class ="footercontent">
<p><span class="credits">&copy; 2012 Goal Setter | <a style="color:#fff; text-decoration:none" href="#"></a><a style="color:#fff; text-decoration:none"  href="#">App Settings</a> | <a style="color:#fff; text-decoration:none" href="#">About</a></span><br /></p>
</div>
</div>
  </div>
</body>
</html>
